config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get 'ajax/index'
  get 'ajax/data'
  post 'ajax/data'

  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  resources :answers
  resources :questions
  get 'questionary_results/calc/:id', to: 'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'
  
  resources :mycontacts
  
  get 'blogs/inndex'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show
  '
  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'
  
  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'

  
  get 'messages/index'
  get 'messages', to: 'messages#index'

  get 'messages/add'
  post 'messages/add', to: 'messages#create'

  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'

  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'


  get 'cards/index'
  get 'cards', to: 'cards#index'

  get 'cards/add'
  post 'cards/add'

  get 'crards/:id', to: 'cards#show'

  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'

  get 'cards/delete/:id' , to: 'cards#delete'

  get 'people/index'
  get 'people', to: 'people#index'

  get 'people/add'
  post 'people/add', to: 'people#create'

  get 'people/:id' , to: 'people#show'

  get 'people/edit/:id', to: 'people#edit'
  patch 'people/edit/:id', to: 'people#update'
  
  get 'people/delete/:id', to: 'people#delete'

  get 'people/find'
  post 'people/find'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	get 'dengonban' , to: 'dengonban#index'
  	post 'dengonban' , to: 'dengonban#index'
  	get 'dengonban/index'
  	post 'dengonban/index'

	get 'helo/index'
  	get 'helo' , to: 'helo#index'
  	get 'helo/other'
  	post 'helo', to: 'helo#index'
  	post 'helo/index'

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question

	validates :content, :name, presence: {message:'は、必須項目です。'}
end

app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
	validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
	has_many :blogpost

	validates :name, presence: {message:'は、必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
	belongs_to :bloggenre

	validates :title, :content, presence: {message:'は、必須項目です。'}
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	validates :Message, presence: {message:'を書いてください。'}
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
	validates :name, presence: {message:'は、必須項目です。'}
	validates :age, numericality: {message:'は、数字で入力ください。'}
	validates :nationality, inclusion: {in: [true, false], message:'は、数字で入力ください。真偽値です。'}
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :message

	validates :name, presence: true
	validates :age, numericality: true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answer

	validates :content, :name,  presence: {message:'は、必須項目です。'}
end

app/models/questionary.rb
class Questionary < ApplicationRecord
	has_many :questionary_item
	has_many :questionary_result
end

app/models/questionary_item.rb
class QuestionaryItem < ApplicationRecord
	belongs_to :Questionary
	has_many :questionary_choice
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  layout 'questions'
  # GET /questions
  # GET /questions.json
  def index
    @questionaries = Question.all.order ('created_at: :desc')
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
    @answer.question_id = params[:id]
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    redirect_to '/questions'
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/questions' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    redirect_to '/questions'
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
      redirect_to '/questions'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :name, :finished)
    end
end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/dengonban_helper.rb
module DengonbanHelper
end

app/helpers/helo_helper.rb
module HeloHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, cols:40, rows:10 %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <%= f.hidden_field :finished, { value:false } %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_form2.html.erb
<%= form_for(answer) do |f| %>
	<% if answer.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(answer.errors.count, "error")%>prohibited this answer from being saved:</h2>
			<ul>
				<% answer.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.hidden_field :question_id, {value: answer.question_id} %>

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :content %>
		<%= f.text_area :content, cols:40, rows:5 %>
	</div>
	<br>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>質問リスト</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Finished</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.finished ? '終了' : '受付中' %></td>
        <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h1>質問と回答</h1>

<div class="question">
	<h2 class="title">
		<%= @question.title %>
	</h2>
	<p class="content">
		<%= @question.content %>
	</p>
	<p class="q_name">
		<%= @question.name %>
	</p>
	<span class="<%= @question.finished ? 'finished' : 'not_finished' %>"><%= @question.finished ? '終了' : '受付中' %>
	</span>
</div>

<% if @question.finished? == false then %>
	<div class="answer_form">
		<h2>＊回答する</h2>
		<%= render 'form2', answer: @answer %>
	</div>
<% end %>

<h2>＊これまで寄せられた回答</h2>

<% if @question.answer.count == 0 then %>
	<p class="answer">＊まだありません。</p>
<% else %>
	<% @question.answer.reverse_each do |re| %>
		<p class="answer">
		<%= re.content + '(' + re.name + ')' %>
	    </p>
	<% end %>
<% end %>