config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  get 'ajax/index'
  get 'ajax/data'
  post 'ajax/data'

  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  resources :answers
  resources :questions
  get 'questionary_results/calc/:id', to: 'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'
  
  resources :mycontacts
  
  get 'blogs/inndex'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show
  '
  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'
  
  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'

  
  get 'messages/index'
  get 'messages', to: 'messages#index'

  get 'messages/add'
  post 'messages/add', to: 'messages#create'

  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'

  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'


  get 'cards/index'
  get 'cards', to: 'cards#index'

  get 'cards/add'
  post 'cards/add'

  get 'crards/:id', to: 'cards#show'

  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'

  get 'cards/delete/:id' , to: 'cards#delete'

  get 'people/index'
  get 'people', to: 'people#index'

  get 'people/add'
  post 'people/add', to: 'people#create'

  get 'people/:id' , to: 'people#show'

  get 'people/edit/:id', to: 'people#edit'
  patch 'people/edit/:id', to: 'people#update'
  
  get 'people/delete/:id', to: 'people#delete'

  get 'people/find'
  post 'people/find'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	get 'dengonban' , to: 'dengonban#index'
  	post 'dengonban' , to: 'dengonban#index'
  	get 'dengonban/index'
  	post 'dengonban/index'

	get 'helo/index'
  	get 'helo' , to: 'helo#index'
  	get 'helo/other'
  	post 'helo', to: 'helo#index'
  	post 'helo/index'

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question

	validates :content, :name, presence: {message:'は、必須項目です。'}
end

app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
	validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
	has_many :blogpost

	validates :name, presence: {message:'は、必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
	belongs_to :bloggenre

	validates :title, :content, presence: {message:'は、必須項目です。'}
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	validates :Message, presence: {message:'を書いてください。'}
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
	validates :name, presence: {message:'は、必須項目です。'}
	validates :age, numericality: {message:'は、数字で入力ください。'}
	validates :nationality, inclusion: {in: [true, false], message:'は、数字で入力ください。真偽値です。'}
end

app/models/person.rb
class Person < ApplicationRecord
	has_many :message

	validates :name, presence: true
	validates :age, numericality: true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answer

	validates :content, :name,  presence: {message:'は、必須項目です。'}
end

app/models/questionary.rb
class Questionary < ApplicationRecord
	has_many :questionary_item
	has_many :questionary_result
end

app/models/questionary_choice.rb
class QuestionaryChoice < ApplicationRecord
	belongs_to :questionary_item

	validates :content, :value, presence: {message:'は、必須項目です。'}
	validates :value, numericality: {message:'は、数字で入力ください。'}
end

app/models/questionary_item.rb
class QuestionaryItem < ApplicationRecord
	belongs_to :Questionary
	has_many :questionary_choice
end

app/controllers/questionary_choices_controller.rb
class QuestionaryChoicesController < ApplicationController
  before_action :set_questionary_choice, only: [:show, :edit, :update, :destroy]

  # GET /questionary_choices
  # GET /questionary_choices.json
  def index
    @questionary_choices = QuestionaryChoice.all
  end

  # GET /questionary_choices/1
  # GET /questionary_choices/1.json
  def show
  end

  # GET /questionary_choices/new
  def new
    @questionary_choice = QuestionaryChoice.new
    @questionary_choice.questionary_item_id = params[:id]
    @questionary_item = QuestionaryItem.find params[:id]
  end

  # GET /questionary_choices/1/edit
  def edit
  end

  # POST /questionary_choices
  # POST /questionary_choices.json
  def create
    @questionary_choice = QuestionaryChoice.new(questionary_choice_params)

    respond_to do |format|
      if @questionary_choice.save
        format.html { redirect_to '/questionary_choices/new' + @questionary_choice.questionary_item_id.to_s }
        format.json { render :show, status: :created, location: @questionary_choice }
      else
        format.html { render :new }
        format.json { render json: @questionary_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionary_choices/1
  # PATCH/PUT /questionary_choices/1.json
  def update
    respond_to do |format|
      if @questionary_choice.update(questionary_choice_params)
        format.html { redirect_to @questionary_choice, notice: 'Questionary choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionary_choice }
      else
        format.html { render :edit }
        format.json { render json: @questionary_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionary_choices/1
  # DELETE /questionary_choices/1.json
  def destroy
    @questionary_choice.destroy
    respond_to do |format|
      format.html { redirect_to questionary_choices_url, notice: 'Questionary choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionary_choice
      @questionary_choice = QuestionaryChoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def questionary_choice_params
      params.require(:questionary_choice).permit(:content, :value, :questionary_item_id)
    end
end

app/helpers/ajax_helper.rb
module AjaxHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/helo_helper.rb
module HeloHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/questionary_choices_helper.rb
module QuestionaryChoicesHelper
end

app/views/questionary_choices/_form.html.erb
<%= form_with(model: questionary_choice, local: true) do |form| %>
  <% if questionary_choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionary_choice.errors.count, "error") %> prohibited this questionary_choice from being saved:</h2>

      <ul>
      <% questionary_choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :questionary_item_id %>
    <%= form.number_field :questionary_item_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questionary_choices/edit.html.erb
<h1>Editing Questionary Choice</h1>

<%= render 'form', questionary_choice: @questionary_choice %>

<%= link_to 'Show', @questionary_choice %> |
<%= link_to 'Back', questionary_choices_path %>

app/views/questionary_choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questionary Choices</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Value</th>
      <th>Questionary item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questionary_choices.each do |questionary_choice| %>
      <tr>
        <td><%= questionary_choice.content %></td>
        <td><%= questionary_choice.value %></td>
        <td><%= questionary_choice.questionary_item_id %></td>
        <td><%= link_to 'Show', questionary_choice %></td>
        <td><%= link_to 'Edit', edit_questionary_choice_path(questionary_choice) %></td>
        <td><%= link_to 'Destroy', questionary_choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Questionary Choice', new_questionary_choice_path %>

app/views/questionary_choices/new.html.erb
<h1>選択肢の作成</h1>
<p>「<%= @questionary_item.content %>」の選択肢</p>

<%= render 'form', questionary_choice: @questionary_choice %>

<%= link_to '次の質問を作成する', '/questionary_items/new/' + @questionary_item.questionary_id.to_s %>

app/views/questionary_choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @questionary_choice.content %>
</p>

<p>
  <strong>Value:</strong>
  <%= @questionary_choice.value %>
</p>

<p>
  <strong>Questionary item:</strong>
  <%= @questionary_choice.questionary_item_id %>
</p>

<%= link_to 'Edit', edit_questionary_choice_path(@questionary_choice) %> |
<%= link_to 'Back', questionary_choices_path %>